const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const http=require('node:http');
const server=http.createServer(async(req,res)=>{try{const name=new URL(req.url,'http://localhost').pathname.slice(1)||'index.html';const file=path.resolve(__dirname,'..',name);if(!file.startsWith(path.resolve(__dirname,'..')+'/'))throw Error('Invalid path');res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':name.endsWith('.pdf')?'application/pdf':'text/html');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});
const root=path.resolve(process.env.REPORT_TEST_OUT||'/tmp/lumen-sopralluogo-test');
async function ink(page){await page.waitForSelector('#signDialog[open]');const box=await page.locator('#signaturePad').boundingBox();await page.mouse.move(box.x+25,box.y+65);await page.mouse.down();for(const [x,y] of [[70,25],[55,110],[115,45],[90,125],[155,80],[215,90]])await page.mouse.move(box.x+x,box.y+y,{steps:4});await page.mouse.up();await page.click('#confirmSignature');await page.waitForFunction(()=>!document.getElementById('signDialog').open);}
async function exported(page,id,filename){const wait=page.waitForEvent('download');await page.click(id);const file=await wait;const out=path.join(root,filename);await file.saveAs(out);return out;}
(async()=>{await new Promise(resolve=>server.listen(8766,'127.0.0.1',resolve));await fs.mkdir(root,{recursive:true});for(const engine of (process.env.REPORT_ENGINES||'chromium,webkit').split(',')){
 const browser=await({chromium,webkit}[engine]).launch({headless:true,...(engine==='chromium'&&process.env.REPORT_BROWSER_PATH?{executablePath:process.env.REPORT_BROWSER_PATH}:{})});const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});const desktop=await context.newPage();const errors=[];desktop.on('pageerror',e=>errors.push(e.message));desktop.on('dialog',d=>d.accept());await desktop.goto('http://127.0.0.1:8766/sopralluogo.html');
 await desktop.fill('#ragione_sociale','AZIENDA DI PROVA');await desktop.fill('#sede_unita_produttiva_e_indirizzo','ROMA - SEDE DI PROVA');await desktop.fill('#datore_di_lavoro_delegato_presente','PRESENTE DI PROVA');await desktop.fill('#rspp_presente','RSPP DI PROVA');await desktop.fill('#rls_rlst_presente','RLS DI PROVA');await desktop.fill('#conclusioni_del_medico_competente','TEST DI IMPAGINAZIONE E FIRME. DATI FITTIZI.');await desktop.locator('#conclusioni_del_medico_competente').blur();
 const datore=desktop.locator('.signer').nth(0);await datore.getByRole('button',{name:'FIRMA SU IPHONE',exact:true}).click();await desktop.waitForSelector('#qrDialog[open]');const url=await desktop.locator('#qrLink').getAttribute('href');const req=JSON.parse(Buffer.from(new URL(url).hash.slice(7),'base64').toString('utf8'));assert.equal(req.name,'PRESENTE DI PROVA');await desktop.click('#closeQr');assert(await desktop.locator('#ragione_sociale').evaluate(e=>e.readOnly));
 const phoneContext=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const phone=await phoneContext.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(url);await phone.click('#phoneSign');await ink(phone);assert.match(await phone.locator('#phoneStatus').innerText(),/ACQUISITA/);const sig=await exported(phone,'#phoneDownload',engine+'-signature.json');await phone.reload();assert(await phone.locator('#phoneDownload').isVisible());
 const bad=JSON.parse(await fs.readFile(sig,'utf8'));bad.reportId='wrong-report';const badPath=path.join(root,engine+'-wrong.json');await fs.writeFile(badPath,JSON.stringify(bad));await desktop.setInputFiles('#receive',badPath);await desktop.waitForFunction(()=>document.getElementById('status').textContent.includes('altra relazione'));assert.equal(await desktop.locator('.signature-preview').count(),0);
 await desktop.setInputFiles('#receive',sig);await desktop.waitForFunction(()=>document.querySelectorAll('.signature-preview').length===1);assert.match(await desktop.locator('#status').innerText(),/FIRME SALVATE/);await desktop.reload();await desktop.click('#archive');await desktop.locator('#archiveList button').first().click();assert.equal(await desktop.locator('.signature-preview').count(),1);
 for(const i of [1,2]){await desktop.locator('.signer').nth(i).getByRole('button',{name:'FIRMA QUI',exact:true}).click();await ink(desktop);}
 // The physician can stamp after participants have signed.
 await desktop.click('#addDoctor');assert(await desktop.locator('#doctorPreview').isVisible());await desktop.click('#pdf');await desktop.waitForSelector('#downloadPanel:not([hidden])');const pdf=await exported(desktop,'#savePdf',engine+'-signed.pdf');const data=await exported(desktop,'#export',engine+'-report.json');
 await desktop.click('#new');assert.equal(await desktop.locator('.signature-preview').count(),0);assert(!(await desktop.locator('#doctorPreview').isVisible()));await desktop.setInputFiles('#import',data);await desktop.waitForFunction(()=>document.querySelectorAll('.signature-preview').length===3);assert.equal(await desktop.locator('.signature-preview').count(),3);await desktop.click('#save');await desktop.click('#pdf');await desktop.waitForSelector('#downloadPanel:not([hidden])');await desktop.screenshot({path:path.join(root,engine+'-desktop.png'),fullPage:true});
 await desktop.click('#edit');assert.equal(await desktop.locator('.signature-preview').count(),0);await desktop.fill('#conclusioni_del_medico_competente','TESTO MODIFICATO');await desktop.setInputFiles('#receive',sig);await desktop.waitForFunction(()=>document.getElementById('status').textContent.includes('Nessuna richiesta'));assert.match(await desktop.locator('#status').innerText(),/Nessuna richiesta/);
 await desktop.fill('#conclusioni_del_medico_competente','TESTO TROPPO LUNGO '.repeat(150));await desktop.click('#pdf');await desktop.waitForFunction(()=>document.getElementById('status').textContent.includes('troppo lungo'));assert(!(await desktop.locator('#downloadPanel').isVisible()));
 await desktop.fill('#conclusioni_del_medico_competente','TESTO DI PROVA');await desktop.click('#save');await desktop.setViewportSize({width:390,height:844});assert(await desktop.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await desktop.screenshot({path:path.join(root,engine+'-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);
 console.log(engine+': PASS separate-device QR/file handoff, mismatch rejection, archive reload, three signatures, physician stamp, PDF, JSON roundtrip, revision invalidation, overflow prevention, mobile layout');await browser.close();
 }server.close();} )().catch(e=>{console.error(e);server.close();process.exit(1);});
